[package]
name = "rust-leibniz"
version = "0.1.0"
authors = ["Lari Liuhamo <lari.liuhamo@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "^1.16.0"
threadpool = "^1.8.1"
crossbeam = "^0.8.4"
